### ISSUE TITLE
Excluded URLs aren't saving

### ISSUE THREAD

**Issue by gouthamravee** [internetarchive/wayback-machine-webextension#1019]
**Describe the bug**
Adding exclude urls doesn't save. 

**To Reproduce**
1. Go to 'exclude urls' page
2. add url "*.gouthamravee.com"
3. hit save
4. close window
5. then return to 'exclude urls' page

**Expected behavior**
After hitting save and returning to the 'exclude urls' page, I am expecting to see the url pattern I added earlier. 

**Screenshots**
https://imgur.com/a/f1qw0Nk  - here's a screen recording of it happening

**Environment (please complete the following information):**
 - Webextension version: 3.2
 - Browser + version: Firefox 123.0.1 (64-bit)
 - OS + version: Windows 11 x64 22H2 22621.3235

**Additional context**
I want to make sure I have all my private domains excluded before I enable auto save. The domains are private and don't exist on the public internet, or at least don't lead to my private services. My main worry is screenshots or any html content of the page being sent to the web archive.

**Comment by cgorringe** [comment]
Hi @gouthamravee Thank you for your detailed bug report, and especially the video!

The Good News: If your websites can't be viewed on the public Internet, then they cannot be saved by the Wayback Machine.

The Not-so-good News: I'm having trouble recreating this bug, but can tell from your video that it's quite real! I tested this on macOS and not Windows though. Since it's working for me, I'm having a hard time debugging the possible cause.

Can I ask for your help to test one thing? Would you check your Settings under Sync, and tell me if that is turned ON or not? If you are signed in to Sync, could you try signing out and test the Excluded URLs feature again?

Thank you.

**Comment by cgorringe** [comment]
@gouthamravee Thanks for following up with this test.

I had a hypothesis that when Sync is turned on, it causes a delay in saving the URLs, and what happens is that the window closes before the saving takes place. If this is true, I should have the fix!

The URLs aren't checked if they are valid or public domains, so that shouldn't make any difference.

**Comment by cgorringe** [comment]
@gouthamravee if you would do one more thing and test out this bug fix, I'd appreciate it!

1. First [download this ZIP file](https://github.com/internetarchive/wayback-machine-webextension/archive/refs/heads/storage-set.zip)
2. Then follow these directions: [Installing the Latest Build from Source](https://github.com/internetarchive/wayback-machine-webextension/tree/storage-set?tab=readme-ov-file#installing-the-latest-build-from-source)

Let us know if that fixes the bug with Sync turned On!

**Comment by gouthamravee** [comment]
Worked perfectly. Thank you!
