### ISSUE TITLE
Archive count and dates not displayed

### ISSUE THREAD

**Issue by Zepfanman** [internetarchive/wayback-machine-webextension#1051]
I assume this is related to the DDOS attack on October 11th. Will this likely start working again once the Wayback Machine is fully back online?
https://mastodon.archive.org/@internetarchive/113319133973800297

**Comment by cgorringe** [comment]
Yeah, the APIs are still down even though the Wayback Machine is partially running, which is preventing the count and dates from displaying. It will come back online once everything else is.

**Comment by panda667** [comment]
I might have the same problem. I don't remember exactly when the extension stopped working; it was a few weeks ago. The dialog pops up, but nothing happens when I click on the 'save now' button on the extension pop-up or the right-click menu. The auto-save doesn't work now either. 

I am using Firefox 131 on Windows 11.
I recently updated to Win 11 from 10. Could this be the problem?

**Comment by cgorringe** [comment]
It's the server APIs that are still down due to the cyberattack. We're very sorry that this is taking so long to repair.

**Comment by panda667** [comment]
*The firefox extension is working for me.* It started partially working
yesterday and works perfectly today.
--
***@***.***

**Comment by panda667** [comment]
I'm not logged in, and yet I can save pages. Is your browser completely up
to date?
--
***@***.***

**Comment by cgorringe** [comment]
It appears to work while logged out, but not while logged in. You shouldn't need to delete the extension though, simply click on the Logout icon in the lower-right corner. Although, Save Page Now also got stuck waiting forever when I tried it. I'll report the issues.

**Comment by cgorringe** [comment]
The Wayback Count and Last Saved Date are now working again.
