### ISSUE TITLE
Auto-Update Previously Saved Pages

### ISSUE THREAD

**Issue by weirdalsuperfan** [internetarchive/wayback-machine-webextension#673]
**Is your feature request related to a problem/ issue? Please describe.**
So a cryptocurrency I (thankfully) didn't invest in recently exit-scammed, but upon checking their website, which I believe I had visited on my computer, only an old version from before their actual website was up was saved by the wayback machine, so there's little record of them beyond Google's image and search results cache, etc. All that the wayback machine had was like this domain name search result webpage or something.

Basically, websites can change, so just because they're saved doesn't mean they've REALLY been saved.

**Describe the solution you'd like**
Since there's no easy way for you to know if a website has been properly saved (you'd have to check all the snapshots manually), I'd like an auto-update option to save webpages even if they already exist.

**Describe alternatives you've considered**
I've considering making the user manually save the page, but that kind of defeats the purpose of this extension, so...yeah.

**Additional context**
The auto-update could consider: when the last snapshot was taken (more than a month ago? maybe it's changed), how many snapshots there have been (only one? might want to save to be safe), whether the page has changed since the last save (not sure if you can check this...), whether the page has ever been saved by you/your browser before (no? might want to save it just in case)

**Comment by cgorringe** [comment]
Since we DO have an auto-save feature, but right now it only saves if the page had never been saved before. But since the check for this also returns a timestamp when it was last saved by the Wayback Machine, it wouldn't be that hard to implement. It's just a matter of adding a field to the Settings, or maybe a dropdown box to choose how long ago since the last snapshot. (e.g. "1 month", "1 year")

Thanks for the suggestion!
