### ISSUE TITLE
Bulk save feature breaks because extension logs out

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/wayback-machine-webextension#690]
Sometimes when I'm saving multiple pages using the 'Bulk save' feature, at some point it stops working due to it automatically **logging out of Internet Archive**.

![image](https://user-images.githubusercontent.com/66422959/101171863-59c6a500-367b-11eb-9dbf-1bee60285c62.png)

Why does the extension log my account out every 15-30 minutes? Is this because Microsoft Edge is suspicious of the developer-unpacked extension or is it a security feature?

**Comment by cgorringe** [comment]
Thanks for catching this bug! I haven't encountered it before, likely because I don't have Edge on my Mac so it gets tested the least on that browser. The code isn't written to auto-logout, so I'm guessing it's something specific to Edge that's causing this.

Another possibility is if you were on the archive.org website and happened to log out there while the Bulk Save was going on, since it uses the same cookie which would get cleared if you logged out there.

Obviously I need to install Edge on my Mac to debug this...

**Comment by Melonadev** [comment]
I'm logged into Internet Archive website on Edge all the time, and I checked that I was still logged into it when this issue occurred.

But every time I start Microsoft Edge, a message pops up at the extension bar, "Disable developer mode extensions", pointing to this extension. Does this occur in other browsers as well?

**Comment by andrizmitnick** [comment]
btw this issue also happens on chrome canary

**Comment by krackers** [comment]
I'm seeing this as well. I think some of the warnings are spurious because the extension shows the "looks like you aren't logged in" on any error, even if the underlying error isn't due to that. For instance, when calling the /status endpoint if IA return with "error:job-failed" then that will propagate up and cause the message to be displayed.

**Comment by cgorringe** [comment]
Thanks everyone for testing and reporting this bug! Looks like we may need to better check for errors and pause the bulk saving so they don't cascade.

**Comment by anishsarangi** [comment]
Thanks everyone for reporting this bug. I will look into this. Thank you !

**Comment by cgorringe** [comment]
This is likely fixed now, but could be tested to make sure.

**Comment by contextnerror** [comment]
I haven't been trying to use bulk save, but I've also been noticing the extension seems to be logging me out for no reason after a certain amount of time. I don't know exactly how long since I only ever notice when I open it up and save page now is suddenly greyed out. This is happening in the latest version of google chrome.

**Comment by Melonadev** [comment]
The latest version (currently) is fully functional, and it doesn't even ask me to log in at all.

**Comment by weirdalsuperfan** [comment]
I'm not sure if the version I'm downloading from github isn't actually the latest version, but I've tried downloading it twice in the last few months, and both times I've installed it I constantly get logged out for no reason. At first I thought it happened when I changed IP addresses because of my VPN, but it actually seems to happen after even just a few hours no matter what I'm doing! I have no idea when this started, but I do know that there are now countless (probably many months' worth) of pages that haven't been saved by the extension because of this bug. Somebody please provide a fix!!!

**Comment by cgorringe** [comment]
Thanks for the report @weirdalsuperfan. It would be useful to know what version of the extension you were using (can see on the browser's Extensions screen, or the extensions About page (small "i" icon along bottom)) Also please download the latest version from Github.

**Comment by weirdalsuperfan** [comment]
@cgorringe The version of the extension I had been using (on Chrome) as installed from the latest code downloaded from github gives "2.999.7" as its version number. Is that right? I uninstalled that and installed the latest version (2.999.9) just now. Now bulk save seems to grey out when I import bookmarks or add URLs, and it says something like "-293 left out of 25". Otherwise if I don't add anything, it says "25 left out of 25" (perhaps the number of tabs I have open?) but when I click it it just says I haven't added any URLs.

**Comment by cgorringe** [comment]
Thanks @weirdalsuperfan for your input!
I just added a limit to Bulk Save to allow at max 25 URLs and your response suggests to me that I should reword that line, so thanks!

**Comment by Melonadev** [comment]
As long as I'm logged in into archive.org, this extension doesn't forget. And the Bulk Save worked decently before the limit was introduced, sometimes even for hundreds of URLs. Why was the limit even introduced again?

**Comment by cgorringe** [comment]
I'm glad to see that it isn't logging out for you @Melonadev! It doesn't log me out either, but sounds like it may for some people.

Since this is a work in progress we'll likely disable the Bulk Save feature when launching on the stores initially due to concerns including server load (since it takes up a lot) which is why we implemented a way to limit the number of URLs. Right now it works fine because only a few people would download and install from Github. I'll see if I can include some way for yourselves (our valued testers!) to continue using the feature without limits, but also not up to me to decide...

**Comment by cgorringe** [comment]
extension shouldn't logout now for a year. Fixed in #792

**Comment by weirdalsuperfan** [comment]
@cgorringe  Was the Bulk Save feature disabled? Any way to get it back?

**Comment by cgorringe** [comment]
@weirdalsuperfan Yes, unfortunately we had to disable it as it would take up too many resources on our servers if too many used it at the same time. I don't know if or when it'd be restored.
