### ISSUE TITLE
False 404 popup

### ISSUE THREAD

**Issue by anishsarangi** [internetarchive/wayback-machine-webextension#748]
**Describe the bug**
Sometimes, the 404 popup is showing on a non-404 URL. 

<img width="1427" alt="Screenshot 2021-05-17 at 11 55 50 PM" src="https://user-images.githubusercontent.com/15776213/118726293-bba45100-b84e-11eb-8eb5-437141a2cd8e.png">

**To Reproduce**
1. Go to https://www.creativebloq.com/web-design/best-404-pages-812505
2. Click on any sample 404 URL on the page (click and open link in a new tab)
3. User will see the 404 banner on the current window (not in the other tab where it should show)

**Expected behavior**
User should see the 404 banner on the correct tab.

**Comment by cgorringe** [comment]
Verified bug occurs in Chrome.

Instead of using the above link (which loads up a ton in the background) you can go here:
https://github.com/internetarchive/wayback-machine-webextension/blob/master/TESTING_GUIDE.md

Then right-click one of the 404 links > "Open Link in New Tab", which in *my* browser will open the tab *behind* while remaining on the current page. This causes the 404 banner to display in the current page rather than the intended page that is opening in the background. (If you select "Open Link in New Window", the banner displays in the correct window.)

Then when you go select the other tab, the banner isn't displaying there, where it should be.

**Comment by cgorringe** [comment]
Also this error in `archive.js` line ~ 1:
`Uncaught SyntaxError: Identifier 'gCloseClicked' has already been declared`

**Comment by anishsarangi** [comment]
The issue is also happening in firefox version.

<img width="1245" alt="Screenshot 2021-05-19 at 7 59 12 AM" src="https://user-images.githubusercontent.com/15776213/118748115-e1dee680-b878-11eb-8d9a-3f4f8d63e4cb.png">
