### ISSUE TITLE
Auto-Save New Bookmarks

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-webextension#749]
This is an enhancement to the existing Auto Save feature, where an option is added to Auto Save whenever a user saves a bookmark. Perhaps add a checkbox in Settings.

Idea from @vbanos - thanks!

**Comment by cgorringe** [comment]
See also #673 Auto-Update Previously Saved Pages.

**Comment by anishsarangi** [comment]
Some resource: 
https://developer.chrome.com/docs/extensions/reference/bookmarks/#event-onCreated

**Comment by nahoj** [comment]
I would also appreciate such a feature.

I don't want to use Auto Save because I don't want an extension to track every page I read, but whenever I bookmark a page it's typically somewhat important to me so I'd appreciate it if it was saved.

Upon failure the user could be notified and offered to ignore future bookmarks on that domain name (useful for intranets and websites that require authentication).

**Comment by cgorringe** [comment]
@nahoj Thanks for your input! I think it would be a good addition.
