### ISSUE TITLE
The add-on causes Wikipedia to resize on Firefox

### ISSUE THREAD

**Issue by unbeatable-101** [internetarchive/wayback-machine-webextension#756]
**Describe the bug**
If you have the add-on enabled, it causes Wikipedia to resize after you load the site

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://en.wikipedia.org
2. Look for the page resizing
3. Disable the add-on from `about:addons`
4. Reload the page again and see it doesn't resize

**Expected behaviour**
The page doesn't resize

**Videos**

https://user-images.githubusercontent.com/58151048/127813534-b4dda7ad-43a7-46ee-8578-a0fba10e3a3f.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.0 Beta (21A5294g)
 - Browser: Firefox Nightly
 - Version: 92.0a1 (2021-08-01) (64-bit)

**Comment by cgorringe** [comment]
Bug tested and verified to occur on Wikipedia using latest webextension (3.0) on both Chrome and Firefox.

On Firefox: Just like in the video, clicking Reload would increase the font size on the page briefly, then immediately go back to default font size. Doesn't do this when the extension is unloaded.

On Chrome: Shrinks the page's font size permanently when on. Turn off the extension, goes back to larger font size.

Thanks for the bug report!

**Comment by cgorringe** [comment]
Figured out why this occurs is due to **style.css** being inserted into Wikipedia pages due to `manifest.json`. Fix would be to only include minimum necessary for the icon popups that are embedded in the page. **style.css** is a massive file. Don't need all that.

**Comment by cgorringe** [comment]
Related to this issue: 

There's a bug in Safari regarding manifest.js: Under "content_scripts" the "matches" field appears to be ignored by Safari and js and css files in this section are inserted in ALL websites instead of just Wikipedia. Seems to only occur when "Always Allow on Every Website..." button is selected in preferences (which is recommended) but this causes all sorts of problems on websites.

Above should be fixed once this issue is fixed.

**Comment by cgorringe** [comment]
Bug specific to Safari above may have been fixed in Safari 15.0.

**Comment by cgorringe** [comment]
fixed #794
