### ISSUE TITLE
Twitter/autosave issues

### ISSUE THREAD

**Issue by newsjunkie247** [internetarchive/wayback-machine-webextension#940]
Not sure if this has to do with Twitter, but with autosave enabled on Firefox/Windows 10, the confirmation of the saved page on Twitter always seems to lag a long time compared to the confirmation for the saving of other pages.

**Comment by newsjunkie247** [comment]
By confirmation I mean when the Number 1 indicator appears on the icon.

**Comment by newsjunkie247** [comment]
Maybe there needs to be another icon indicator to show that autosave has started on a page?

**Comment by cgorringe** [comment]
Thanks for this report.

There is a red "hour-glass" (it's tiny) icon indicator that should display when auto-save (or any saving) starts. The red "1" badge would appear after saving finishes and a tiny green checkbox icon appears. It may be hard to see because when Wayback Count is turned on and shows the "0" red badge, it partially covers over the icon. Maybe one tweak I can make is to hide the count badge while it is saving, to make it easier to see the icon.

**Comment by cgorringe** [comment]
Yes, it may also be that saving takes extra long on Twitter.
Thanks, I'll let the team know.
