### ISSUE TITLE
Clicking on the "Save Page Now" button does nothing at all

### ISSUE THREAD

**Issue by AlexanderRitter02** [internetarchive/wayback-machine-webextension#983]
**Describe the bug**
Clicking on the red "Save Page Now" button does nothing at all, no feedback, the button just stays looking the same.
This started happening after upgrading the extension to 3.2 and upgrading Firefox to 109.0, did these updates at the same time.

Strangely, on a fresh Firefox profile the isssue does not appear.
Can I please get help debugging this issue? E.g. can I somehow see **log output** from the extension or something similar?
Since this only seems to happen with my profile the scope of this issue may be minimal, but I would still appreciate _help or suggestions_ on how I could fix it. Thanks.

What I already tried:
- Reinstalling the extension
- Restarting Firefox and PC
- Clearing saved cookies and website data

**Environment:**
 - 3.2
 - Firefox 109.0
 - Windows 10 22H2

**Comment by AlexanderRitter02** [comment]
By the way, when reinstalling the extension and clearing cookies, I was not prompted to login again.
This indicates that I'm not clearing all possible data related to the extension, how would I remove it completely?

**Comment by cgorringe** [comment]
@AlexanderRitter02 Thanks for reporting this. Normally "Save Page Now" does work, but it may be at that instance our servers were not responding, which is why it would work when you tried it again.

To see the console log to help with debugging:
- Go here: Settings > Extensions & Themes > Upper-right Gear icon > Debug Add-ons
  - Or enter this URL: `about:debugging#/runtime/this-firefox`
- Select Extensions.
- Click on Inspect button right of Wayback Machine.
- Select "Console" tab.

The extension has its own persistent storage, which doesn't get cleared normally when clearing cookie data.
- To fully clear login cookies: Select the Logout button (lower-right corner of extension)
- To clear the cache, turn on Private Mode from the extension's settings.

That will clear out all of the extension's data.

**Comment by AlexanderRitter02** [comment]
I don't believe it's the servers not responding, since it worked in another Firefox profile at the same time, and the issue still persists.

About logging out to delete data, I don't see a logout button:
![grafik](https://user-images.githubusercontent.com/42546705/214381675-374f28f4-21fe-4d30-a25a-48476fb46c0e.png)


Not sure what to do right now, since I can't wipe my entire Firefox profile, since I use the history for back reference and research.

**Comment by AlexanderRitter02** [comment]
### Update: Problem solved ✔️ 
As stressed before, this was an issue with my profile.

Solved it by binary testing through user preferences.

**In case someone stumbles upon this:**
- I had **First Party Isolation** enabled, e.g. `privacy.firstparty.isolate` set to true.
- Enabling FPI would consistently remove the logout button in the Wayback extension and produce the described issue
- Solved by resetting `privacy.firstparty.isolate` in about:config

The first party isolation preference is outdated:
```
 * [WARNING] Replaced with network partitioning (FF85+) and TCP (2701),
 * and enabling FPI disables those. FPI is no longer maintained
 ```
 
 Although I was able to solve this myself, thank you for listening and for your patience!

**Comment by cgorringe** [comment]
@AlexanderRitter02 Thanks for investigating this issue!

I added some checks to inform the user while logging in if the extension has any issues accessing cookies, including this case. Thank you.
